python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0013_sat.jpg --mask_path ./plot_output/epoch-1-0.png  --name 0013_sat_early
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0013_sat.jpg --mask_path ./plot_output/epoch-50-0.png  --name 0013_sat_middle
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0013_sat.jpg --mask_path ./plot_output/epoch-100-0.png --name 0013_sat_final
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0062_sat.jpg --mask_path ./plot_output/epoch-1-1.png   --name 0062_sat_early
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0062_sat.jpg --mask_path ./plot_output/epoch-50-1.png  --name 0062_sat_middle
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0062_sat.jpg --mask_path ./plot_output/epoch-100-1.png  --name 0062_sat_final
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0104_sat.jpg --mask_path ./plot_output/epoch-1-2.png   --name 0104_sat_early
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0104_sat.jpg --mask_path ./plot_output/epoch-50-2.png   --name 0104_sat_middle
python3 viz_mask.py --sat_path ../hw1_data/p2_data/validation/0104_sat.jpg --mask_path ./plot_output/epoch-100-2.png  --name 0104_sat_final
